import { Link } from 'react-router-dom'
import { ShieldHalf, FileText, GitFork, Globe, Contact, Network, Skull, MessagesSquare, ArrowRight } from 'lucide-react'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'

const FEATURES = [
  { icon: FileText, title: 'Resume Analyzer', desc: 'Detects PII buried in your resume — phone, address, DOB, ID numbers — before recruiters or scrapers find it.' },
  { icon: GitFork, title: 'GitHub Scanner', desc: 'Scans your public repos for leaked keys, tokens, and secrets in commits and READMEs.' },
  { icon: Globe, title: 'Portfolio Scanner', desc: 'Checks your personal site for exposed contact details, metadata, and hidden links.' },
  { icon: Contact, title: 'LinkedIn Scanner', desc: 'Reviews your public profile for information that enables targeted phishing.' },
  { icon: Network, title: 'Footprint Map', desc: 'Visualizes how your scattered data points connect into one exploitable profile.' },
  { icon: Skull, title: 'Attack Simulation', desc: 'AI-generated phishing and recruiter-scam previews, built from your own exposure — for education, not exploitation.' },
  { icon: MessagesSquare, title: 'AI Privacy Coach', desc: 'Personalized, prioritized fixes generated by Gemini, ranked by urgency.' },
  { icon: ShieldHalf, title: 'Safe Resume Generator', desc: 'Produces a scrubbed, recruiter-safe version of your resume automatically.' },
]

const STEPS = [
  { title: 'Connect a source', desc: 'Upload a resume, or point us at a GitHub username, portfolio URL, or LinkedIn profile.' },
  { title: 'AI analyzes exposure', desc: 'We extract, classify, and score every piece of identifying information we find.' },
  { title: 'See the attack path', desc: 'The footprint map shows how attackers could chain your data into a real exploit.' },
  { title: 'Fix it', desc: 'Follow prioritized, AI-generated recommendations — or generate a safer resume instantly.' },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-base bg-grid text-text-primary">
      <nav className="sticky top-0 z-20 border-b border-border-glass bg-base/70 backdrop-blur-md">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2">
            <ShieldHalf className="h-6 w-6 text-signal-blue" strokeWidth={2.2} />
            <span className="font-display text-lg font-semibold">ShadowAI</span>
          </div>
          <div className="hidden items-center gap-8 text-sm text-text-muted md:flex">
            <a href="#features" className="hover:text-text-primary">Features</a>
            <a href="#how-it-works" className="hover:text-text-primary">How it works</a>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="text-sm text-text-muted hover:text-text-primary">Log in</Link>
            <Link to="/signup"><Button>Get started</Button></Link>
          </div>
        </div>
      </nav>

      <section className="relative overflow-hidden px-6 pb-24 pt-20 text-center">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute left-1/2 top-0 h-96 w-[600px] -translate-x-1/2 rounded-full bg-signal-purple/15 blur-[140px]" />
        </div>
        <div className="relative z-10 mx-auto max-w-3xl">
          <span className="mb-6 inline-block rounded-full glass px-4 py-1.5 font-mono text-xs text-signal-cyan">
            Idea2Impact 2026 — AI Digital Footprint Intelligence
          </span>
          <h1 className="font-display text-4xl font-semibold leading-tight md:text-6xl">
            Know what the internet knows about you{' '}
            <span className="signal-gradient-text">before hackers do</span>
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-lg text-text-muted">
            ShadowAI scans your resume, GitHub, portfolio, and LinkedIn for the exposed data attackers actually use —
            then shows you the attack before it happens.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4">
            <Link to="/signup">
              <Button className="px-7 py-3 text-base">
                Scan your footprint free <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <section id="features" className="mx-auto max-w-7xl px-6 py-20">
        <div className="mb-12 text-center">
          <h2 className="font-display text-3xl font-semibold">One platform, every exposure surface</h2>
          <p className="mt-2 text-text-muted">Most tools check one thing. ShadowAI correlates all of them.</p>
        </div>
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {FEATURES.map(({ icon: Icon, title, desc }) => (
            <Card key={title} className="transition-transform hover:-translate-y-1">
              <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-signal-blue/20 to-signal-purple/20">
                <Icon className="h-5 w-5 text-signal-blue" />
              </div>
              <h3 className="font-display font-semibold">{title}</h3>
              <p className="mt-1.5 text-sm text-text-muted">{desc}</p>
            </Card>
          ))}
        </div>
      </section>

      <section id="how-it-works" className="mx-auto max-w-5xl px-6 py-20">
        <div className="mb-12 text-center">
          <h2 className="font-display text-3xl font-semibold">How it works</h2>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-4">
          {STEPS.map((step, i) => (
            <div key={step.title} className="relative">
              <div className="mb-3 font-mono text-sm text-signal-purple">{String(i + 1).padStart(2, '0')}</div>
              <h3 className="font-display font-semibold">{step.title}</h3>
              <p className="mt-1.5 text-sm text-text-muted">{step.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-6 py-20 text-center">
        <Card className="px-8 py-14">
          <h2 className="font-display text-3xl font-semibold">Ready to see your exposure?</h2>
          <p className="mt-3 text-text-muted">Free to start. Takes under two minutes for your first scan.</p>
          <Link to="/signup" className="mt-6 inline-block">
            <Button className="px-7 py-3 text-base">
              Create your free account <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </Card>
      </section>

      <footer className="border-t border-border-glass px-6 py-8 text-center text-sm text-text-muted">
        © 2026 ShadowAI — Built for Idea2Impact 2026. Educational security tooling.
      </footer>
    </div>
  )
}
